org.xfce.mousepad.preferences.view color-scheme 'dracula'
org.xfce.mousepad.preferences.view highlight-current-line true
org.xfce.mousepad.preferences.view indent-width -1
org.xfce.mousepad.preferences.view show-line-numbers true
org.xfce.mousepad.preferences.window menubar-visible true
org.xfce.mousepad.preferences.window menubar-visible-in-fullscreen 'auto'
org.xfce.mousepad.preferences.window statusbar-visible true
org.xfce.mousepad.preferences.window statusbar-visible-in-fullscreen 'auto'
'org.xfce.mousepad.preferences.view' 'tab-width' 'uint32 4'